apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # if updates are there pull latest image
  nodeSelector:
    disktype: ssd